INSERT INTO CheckDoc.MISTAKE_TYPE (DEFINITION, NAME) VALUES ("Invalid font", "FONT_MISTAKE");
INSERT INTO CheckDoc.MISTAKE_TYPE (DEFINITION, NAME) VALUES ("Invalid font size", "FONT_SIZE_MISTAKE");
INSERT INTO CheckDoc.MISTAKE_TYPE (DEFINITION, NAME) VALUES ("Invalid left intend size", "INTEND_SIZE_MISTAKE");